// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgmqaukeuuebgetlwund.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnbXFhdWtldXVlYmdldGx3dW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MjAxNDMsImV4cCI6MjA2MDA5NjE0M30.RqLpj9VGhvksRPv0OQgH3tmgOdLviuvbS7c_2bK5NE8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);